pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'https://hub.docker.com/'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    dir('client') {
                        sh 'npm install'
                        sh 'npm run build --prod'
                    }
                }
            }
        }

        stage('Dockerize') {
            steps {
                script {

                    docker.withRegistry("${DOCKER_REGISTRY}", "6c5bb7c1-b4ff-4885-accf-f0516ad093bd") {
                        dir('client') {
                            def image = docker.build("maadhar-client:latest")
                            image.push()
                        }
                    }
                }
            }
        }
    }
}
